AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Demo-SageMaker-Studio-EFS-Recovery

Parameters:
  ############### Scenario Testing Param ####################
  MODE:
    Description: Skip Creation of SageMaker Domain
    Type: String
    AllowedValues:
      - SEED
      - NOSEED
    Default: NOSEED
  ############### SSM Bootstrap ####################
  VpcId:
    Description: VPCId of existing Virtual Private Cloud
    Type: String
  SubnetId1:
    Description: SubnetId1 of an existing subnet in the VPC
    Type: String
    ConstraintDescription: must be an existing subnets in the VPC.
  ############### Step Function ####################
  StepFunctionName:
    Type: String
    Description: name of the Step Function
    Default: demo-stepfunction
  SQSName:
    Type: String
    Description: name of the SQS
    Default: demo-sqs
  ############### EventApp ####################
  DDBInitialSeed:
    Description: Select ENABLED only if SageMaker Domain isn't deployed along this stack
    Type: String
    AllowedValues:
      - DISABLED
      - ENABLED
    Default: DISABLED
  ############### Sagemaker ####################
  StudioSpaceName:
    Description: Studio space name
    Type: String
    Default: space-test
  StudioUserProfileName1:
    Description: Studio user1 profile name
    Type: String
    Default: user1
  StudioUserProfileName2:
    Description: Studio user1 profile name
    Type: String
    Default: user2
  ############### Lambda Layer Name ####################
  LambdaLayerName:
    Description: Lambda Layer Name
    Type: String
    Default: "boto3-layer"
  ############### Tagging Parameters ####################
  UID:
    Type: String
    Description: Universal Identifier
    MinLength: 3
    MaxLength: 10
    Default: demo
  Env:
    Type: String
    Description: Env instance of the resource
    AllowedValues:
      - dev
      - qa
      - prd
    Default: dev
  AppName:
    Type: String
    MaxLength: 25
    MinLength: 3
    AllowedPattern: "[a-z][a-z0-9+-=._:/@]*[a-z0-9]"
    ConstraintDescription: Must begin with a lowercase letter and contain only lowercase alphanumeric characters with +-=._:/@
    Description: Name of the application, keep to 15 characters or less
    Default: myapp

Conditions:
  CreateDomainCond: !Equals [ !Ref MODE, 'NOSEED' ]

# Create our resources with separate CloudFormation templates resources:
Resources:
  DemoBootstrap:
    Type: AWS::Serverless::Application
    Properties:
      Location: Infrastructure/Templates/ssm.yaml
      Parameters:
        VpcId: !Ref VpcId
        SubnetId1: !Ref SubnetId1
        LambdaLayerName: !Ref LambdaLayerName
        UID: !Ref UID
        Env: !Ref Env
        AppName: !Ref AppName
  StepFunction:
    Type: AWS::Serverless::Application
    DependsOn: DemoBootstrap
    Properties:
      Location: Infrastructure/Templates/stepfunction.yaml
      Parameters:
        StepFunctionName: !Ref StepFunctionName
        SQSName: !Ref SQSName
        UID: !Ref UID
        Env: !Ref Env
        AppName: !Ref AppName
  EventApp:
    Type: AWS::Serverless::Application
    DependsOn: StepFunction
    Properties:
      Location: Infrastructure/Templates/event-app.yaml
      Parameters:
        DDBInitialSeed: !Ref DDBInitialSeed
        LambdaLayerArn: !GetAtt DemoBootstrap.Outputs.LambdaLayerArn
        UID: !Ref UID
        Env: !Ref Env
        AppName: !Ref AppName
  StudioDomain:
    Type: AWS::Serverless::Application
    Condition: CreateDomainCond
    DependsOn: EventApp
    Properties:
      Location: Infrastructure/Templates/sagemaker-studio-domain.yaml
      Parameters:
        LambdaLayerArn: !GetAtt DemoBootstrap.Outputs.LambdaLayerArn
        UID: !Ref UID
        Env: !Ref Env
        AppName: !Ref AppName
  StudioUser1:
    Type: AWS::Serverless::Application
    Condition: CreateDomainCond
    DependsOn: StudioDomain
    Properties:
      Location: Infrastructure/Templates/sagemaker-studio-user.yaml
      Parameters:
        LambdaLayerArn: !GetAtt DemoBootstrap.Outputs.LambdaLayerArn
        StudioUserProfileName: !Ref StudioUserProfileName1
        UID: !Ref UID
        Env: !Ref Env
        AppName: !Ref AppName
  StudioSpace:
    Type: AWS::Serverless::Application
    Condition: CreateDomainCond
    DependsOn: StudioDomain
    Properties:
      Location: Infrastructure/Templates/sagemaker-studio-space.yaml
      Parameters:
        LambdaLayerArn: !GetAtt DemoBootstrap.Outputs.LambdaLayerArn
        StudioSpaceName: !Ref StudioSpaceName
        UID: !Ref UID
        Env: !Ref Env
        AppName: !Ref AppName